### ISSUE TITLE
Argument 1 must be string, not None when creating TornadoSession

### ISSUE THREAD

**Issue by k4ppa** [gmr/queries#19]
I'm trying to use TornadoSession in my project, but I can't make it work.
When the function TornadoSession() is called it raise the following exception:

```
 Exception in callback <functools.partial object at 0x7fb710f9c2b8>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/queries/tornado_session.py", line 374, in on_connected
        cursor = self._get_cursor(conn)
      File "/usr/local/lib/python2.7/dist-packages/queries/session.py", line 311, in _get_cursor
        cursor_factory=self._cursor_factory)
    TypeError: argument 1 must be string, not None
```

It gives this error even with one of the example found in the documentation:
```
from tornado import gen, ioloop, web
import queries

class MainHandler(web.RequestHandler):

    def initialize(self):
		conf = queries.uri(host='localhost', port=5432, dbname="myDb", user="root", password="pass")
		self.session = queries.TornadoSession(conf)

    @gen.coroutine
    def get(self):
        results = yield self.session.query('SELECT * FROM myTable')
        self.finish({'data': results.items()})
        results.free()
application = web.Application([
    (r"/", MainHandler),
])

if __name__ == "__main__":
    application.listen(8888)
    ioloop.IOLoop.instance().start()
```

What can cause this issue?

**Comment by gmr** [comment]
Wow, old ticket, sorry. I'm not sure what the issue is I can't replicate it with your example. Perhaps an older version of queries that has a bug which has since been fixed?
