### ISSUE TITLE
TornadoSession.validate enters endless loop upon failure

### ISSUE THREAD

**Issue by dave-shawley** [gmr/queries#24]
Not completely sure what is going on here, but when `TornadoSession.validate` is called with a bad password it fails with an exception which is fine except that something is left on the ioloop that eats the CPU alive.  The following script will show the problem when you run it with a DSN that is valid except for the password:
```python
#!/usr/bin/env python
#
import logging
import signal
import sys

import queries
from tornado import gen, ioloop


@gen.coroutine
def main():
    logger = logging.getLogger('main')
    for dsn in sys.argv[1:]:
        logger.info('starting session with dsn=%s', dsn)
        try:
            session = queries.TornadoSession(dsn)
            yield session.validate()
            logger.info('validated')
        except:
            logger.exception('FAILURE FOR %s', dsn)

    while True:
        yield gen.sleep(10)


def sig_handler(*args):
    logging.info('signal handler invoked with %r', args)
    iol = ioloop.IOLoop.instance()
    iol.add_callback_from_signal(iol.stop)


if __name__ == '__main__':
    if len(sys.argv) == 1:
        print('Usage:', sys.argv[0], 'DSN [DSN...]')
        sys.exit(1)

    logging.basicConfig(
        level=logging.DEBUG,
        format='[%(process)d] %(levelname)1.1s - %(name)s: %(message)s')
    signal.signal(signal.SIGINT, sig_handler)
    signal.signal(signal.SIGTERM, sig_handler)
    iol = ioloop.IOLoop.instance()
    iol.add_future(main(), lambda _: None)
    iol.start()
```

When given a valid DSN it will validate the session and sleep until you kill with Ctrl+C.  Give it an invalid password and it will report and error and go into the same sleep cycle with something like the following log:
```
(env) Daves-MBP/queries-play% ./validate.py 'postgresql://postgres:secret2@127.0.0.1:32770/postgres'
[20562] I - main: starting session with dsn=postgresql://postgres:secret2@127.0.0.1:32770/postgres
[20562] D - queries.pool: Creating Pool: ea2750c53184e9ddec80659446cbe6fa (60/25)
[20562] D - queries.tornado_session: Creating a new connection for ea2750c53184e9ddec80659446cbe6fa
[20562] E - main: FAILURE FOR postgresql://postgres:secret2@127.0.0.1:32770/postgres
Traceback (most recent call last):
  File "./validate.py", line 18, in main
    yield session.validate()
  File "/Users/daveshawley/Source/python/queries-play/env/lib/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/daveshawley/Source/python/queries-play/env/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/daveshawley/Source/python/queries-play/env/lib/python3.4/site-packages/queries/tornado_session.py", line 460, in _poll_connection
    state = self._connections[fd].poll()
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"

```

Now run top or similar process monitor and you'll notice that the process is consuming an entire core.  It is not chewing through memory or stranding sockets (verified by `lsof`).  It is simply looping very hard on something.  I ran `sudo dtrace -p 20562 -n 'syscall:::entry'` to see what was going on and it looks like it might be failing to handle a socket error and retrying the connection sequence repeatedly.  The dtrace output settles to:
```
  4    883           workq_kernreturn:entry
  2    941             write_nocancel:entry
  6    873                     kevent:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  0    333                     select:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
  6    873                     kevent:entry
  2    941             write_nocancel:entry
  2    941             write_nocancel:entry
```
repeatedly.  There are no calls to IO traps so I don't think that it is trying a new connection.  It looks like it is simply looping repeatedly.

**Comment by gmr** [comment]
Closed due to removing validate function from TornadoSession
